export default [
  { "id": 1, "name": "George Washington" },
  { "id": 2, "name": "John Adams" },
  { "id": 3, "name": "Thomas Jefferson" },
  { "id": 4, "name": "James Madison" },
  { "id": 5, "name": "James Monroe" },
  { "id": 6, "name": "John Quincy Adams" },
  { "id": 7, "name": "Andrew Jackson" },
  { "id": 8, "name": "Martin Van Buren" },
  { "id": 9, "name": "William Henry Harrison" },
  { "id": 10, "name": "John Tyler" },
  { "id": 11, "name": "James K. Polk" },
  { "id": 12, "name": "Zachary Taylor" },
  { "id": 13, "name": "Millard Fillmore" },
  { "id": 14, "name": "Franklin Pierce" },
  { "id": 15, "name": "James Buchanan" },
  { "id": 16, "name": "Abraham Lincoln" },
  { "id": 17, "name": "Andrew Johnson" },
  { "id": 18, "name": "Ulysses S. Grant" },
  { "id": 19, "name": "Rutherford B. Hayes" },
  { "id": 20, "name": "James A. Garfield" },
  { "id": 21, "name": "Chester A. Arthur" },
  { "id": 22, "name": "Grover Cleveland" }, // Only listed once
  { "id": 23, "name": "Benjamin Harrison" },
  { "id": 24, "name": "William McKinley" },
  { "id": 25, "name": "Theodore Roosevelt" },
  { "id": 26, "name": "William Howard Taft" },
  { "id": 27, "name": "Woodrow Wilson" },
  { "id": 28, "name": "Warren G. Harding" },
  { "id": 29, "name": "Calvin Coolidge" },
  { "id": 30, "name": "Herbert Hoover" },
  { "id": 31, "name": "Franklin D. Roosevelt" },
  { "id": 32, "name": "Harry S. Truman" },
  { "id": 33, "name": "Dwight D. Eisenhower" },
  { "id": 34, "name": "John F. Kennedy" },
  { "id": 35, "name": "Lyndon B. Johnson" },
  { "id": 36, "name": "Richard Nixon" },
  { "id": 37, "name": "Gerald Ford" },
  { "id": 38, "name": "Jimmy Carter" },
  { "id": 39, "name": "Ronald Reagan" },
  { "id": 40, "name": "George H. W. Bush" },
  { "id": 41, "name": "Bill Clinton" },
  { "id": 42, "name": "George W. Bush" },
  { "id": 43, "name": "Barack Obama" },
  { "id": 44, "name": "Donald Trump" },
  { "id": 45, "name": "Joe Biden" }
];
