import random 
from pymongo import MongoClient

from config.database import collection_name

prompts = [
    {"name": "Had a pilot license", "query": {"pilot_certificate": True}},
    {"name": "Was over 6 feet tall", "query": {"height": {"$gt": 72}}},
    {"name": "Owned a dog", "query": {"owned_dog": True}},
    {"name": "Appointed at least 3 judges", "query": {"appointed_judges": {"$gt": 3}}},
    {"name": "Faced impeachment", "query": {"faced_impeachment": True}},
    {"name": "Was assassinated", "query": {"was_assassinated": True}},
    {"name": "Was a former general", "query": {"former_general": True}},
    {"name": "Died in office", "query": {"died_in_office": True}},
    {"name": "Was a former vice president", "query": {"former_vice_president": True}},
    {"name": "Served 2 or more terms", "query": {"served_2more_terms": True}},
    {"name": "Faced an economic crisis", "query": {"faced_economic_crisis": True}},
    {"name": "Served during the Cold War", "query": {"served_cold_war": True}},
    {"name": "Served in the military", "query": {"served_military": True}},
    {"name": "Served during the Revolution", "query": {"served_during_revolution": True}},
    {"name": "Had notable foreign policy", "query": {"notable_foreign_policy": {"$ne": ""}}},
    {"name": "Served amidst infrastructure development", "query": {"served_amidst_infrastructure": True}},
    {"name": "Known for environmental conservation", "query": {"known_environmental_conservation": True}},
    {"name": "Involved in land acquisition", "query": {"involved_land_acquisition": True}},
    {"name": "First lady's name was Elizabeth", "query": {"first_lady_name_elizabeth": True}},
    {"name": "Served as an ambassador to a foreign country", "query": {"served_ambassador": True}},
    {"name": "Did not serve as an ambassador to a foreign country", "query": {"served_ambassador": False}},
    {"name": "Was a lawyer", "query": {"lawyer_previously": True}},
    {"name": "Was a governor", "query": {"governor_previously": True}},
    {"name": "Was a senator", "query": {"senator_previously": True}},
    {"name": "Wrote an autobiography", "query": {"autobiography": True}},
    {"name": "Never wrote an autobiography", "query": {"autobiography": False}},
    {"name": "Received a medal of honor", "query": {"medal_honor": True}},
    {"name": "Had more than 2 sons", "query": {"sons": {"$gt": 2}}},
    {"name": "Had more than 2 daughters", "query": {"daughters": {"$gt": 2}}},
    {"name": "Had more than 3 siblings", "query": {"siblings": {"$gt": 3}}},
    {"name": "Had more than 2 marriages", "query": {"marriages": {"$gt": 2}}},
    {"name": "Served as an ambassador to more than 1 country", "query": {"number_served_ambassador": {"$gt": 1}}},
    {"name": "Inaugurated at age less than 50", "query": {"age_inauguration": {"$lt": 50}}},
    {"name": "Received military awards", "query": {"military_awards": {"$ne": ""}}},
    {"name": "Weighed over 200 pounds", "query": {"weight": {"$gt": 200}}},
    {"name": "Served more than 8 years in office", "query": {"years_in_office": {"$gt": 8}}},
    {"name": "Died at age more than 80", "query": {"death_age": {"$gt": 80}}},
    {"name": "Issued more than 100 executive orders", "query": {"executive_orders": {"$gt": 100}}},
    {"name": "Issued more than 50 vetoes", "query": {"vetoes": {"$gt": 50}}},
    {"name": "Issued more than 30 pardons", "query": {"pardons": {"$gt": 30}}},
    {"name": "Served during wartime", "query": {"served_ww": True}},
    {"name": "First Lady named Elizabeth", "query": {"first_lady_name_elizabeth": True}},
    {"name": "Owned a dog", "query": {"owned_dog": True}},
    {"name": "Had 0 sons", "query": {"sons": 0}},
    {"name": "Had 0 daughters", "query": {"daughters": 0}},
    {"name": "Had 0 siblings", "query": {"siblings": 0}},
    {"name": "Had 0 marriages", "query": {"marriages": 0}},
    {"name": "Inaugurated at age more than 60", "query": {"age_inauguration": {"$gt": 60}}},
    {"name": "Received no military awards", "query": {"military_awards": ""}},
    {"name": "Did not found any companies", "query": {"founded_companies": ""}},
    {"name": "Weighed less than 150 pounds", "query": {"weight": {"$lt": 150}}},
    {"name": "Served less than 4 years in office", "query": {"years_in_office": {"$lt": 4}}},
    {"name": "Died at age less than 60", "query": {"death_age": {"$lt": 60, "$gt": 0}}},
    {"name": "Issued less than 20 executive orders", "query": {"executive_orders": {"$lt": 20}}},
    {"name": "Issued less than 10 vetoes", "query": {"vetoes": {"$lt": 10}}},
    {"name": "Issued less than 5 pardons", "query": {"pardons": {"$lt": 5}}},
    {"name": "Did not serve during a World War", "query": {"served_ww": False}},
    {"name": "Was not assassinated", "query": {"was_assassinated": False}},
    {"name": "First Lady was not named Elizabeth", "query": {"first_lady_name_elizabeth": False}},
    {"name": "Did not sign a notable foreign policy", "query": {"notable_foreign_policy": ""}},
    {"name": "Not involved in infrastructure projects", "query": {"served_amidst_infrastructure": False}},
    {"name": "Not involved in land acquisition", "query": {"involved_land_acquisition": False}},
    {"name": "Did not receive the Medal of Honor", "query": {"medal_honor": False}},
    {"name": "Did not own a dog", "query": {"owned_dog": False}},
    {"name": "Had less than 2 sons", "query": {"sons": {"$lt": 2}}},
    {"name": "Had less than 2 daughters", "query": {"daughters": {"$lt": 2}}},
    {"name": "Had less than 3 siblings", "query": {"siblings": {"$lt": 3}}},
    {"name": "Had less than 1 marriage", "query": {"marriages": {"$lt": 1}}},
    {"name": "Inaugurated at age more than 55", "query": {"age_inauguration": {"$gt": 55}}},
    {"name": "Had a military award", "query": {"military_awards": {"$ne": ""}}},
    {"name": "Weighed more than 180 pounds", "query": {"weight": {"$gt": 180}}},
    {"name": "Served more than 4 years in office", "query": {"years_in_office": {"$gt": 4}}},
    {"name": "Died at age less than 70", "query": {"death_age": {"$lt": 70, "$gt": 0}}},
    {"name": "Issued less than 50 executive orders", "query": {"executive_orders": {"$lt": 50}}},
    {"name": "Issued less than 20 vetoes", "query": {"vetoes": {"$lt": 20}}},
    {"name": "Issued less than 10 pardons", "query": {"pardons": {"$lt": 10}}},
    {"name": "Did not serve during a World War", "query": {"served_ww": False}},
    {"name": "Did not die in office", "query": {"died_in_office": False}},
    {"name": "Had less than 2 siblings", "query": {"siblings": {"$lt": 2}}},
    {"name": "Had only 1 marriage", "query": {"marriages": 1}},
    {"name": "Inaugurated at age less than 40", "query": {"age_inauguration": {"$lt": 40}}},
    {"name": "Founded more than 2 companies", "query": {"founded_companies": {"$gt": 2}}},
    {"name": "Weighed less than 160 pounds", "query": {"weight": {"$lt": 160}}},
    {"name": "Served exactly 4 years in office", "query": {"years_in_office": 4}},
    {"name": "Died at age more than 90", "query": {"death_age": {"$gt": 90}}},
    {"name": "Issued more than 200 executive orders", "query": {"executive_orders": {"$gt": 200}}},
    {"name": "Issued more than 100 vetoes", "query": {"vetoes": {"$gt": 100}}},
    {"name": "Issued more than 50 pardons", "query": {"pardons": {"$gt": 50}}},
    {"name": "Issued more than 100 pardons", "query": {"pardons": {"$gt": 100}}},
    {"name": "Issued more than 500 pardons", "query": {"pardons": {"$gt": 500}}},
    {"name": "Had no nieces or nephews", "query": {"siblings": 0}},
    {"name": "Had less than 1 sibling", "query": {"siblings": {"$lt": 1}}},
    {"name": "Never divorced", "query": {"marriages": {"$lte": 1}}},
    {"name": "Inaugurated at age exactly 50", "query": {"age_inauguration": 50}},
    {"name": "Received multiple military awards", "query": {"military_awards": {"$ne": ""}}},
    {"name": "Weighed more than 210 pounds", "query": {"weight": {"$gt": 210}}},
    {"name": "Served less than 8 years in office", "query": {"years_in_office": {"$lt": 8}}},
    {"name": "Issued no executive orders", "query": {"executive_orders": 0}},
    {"name": "Issued exactly 5 vetoes", "query": {"vetoes": 5}},
    {"name": "Issued 0 pardons", "query": {"pardons": 0}},
    {"name": "Had more than 1 sibling", "query": {"siblings": {"$gt": 1}}},
    {"name": "Had multiple divorces", "query": {"marriages": {"$gt": 1}}},
    {"name": "Inaugurated at age less than 45", "query": {"age_inauguration": {"$lt": 45}}},
    {"name": "Served less than 6 years in office", "query": {"years_in_office": {"$lt": 6}}},
    {"name": "Issued more than 300 executive orders", "query": {"executive_orders": {"$gt": 300}}},
    {"name": "Issued exactly 25 vetoes", "query": {"vetoes": 25}},
    {"name": "Issued less than 15 pardons", "query": {"pardons": {"$lt": 15}}},
    {"name": "Attended Harvard", "query": {"education": {"$in": ["Harvard", "Harvard University", "Harvard College", "Harvard Law School"]}}},
    {"name": "Attended The College of William and Mary", "query": {"education": "College of William and Mary"}},
    {"name": "Attended Yale", "query": {"education": {"$in": ["Yale College", "Yale University", "Yale Law School"]}}},
    {"name": "Did not attend college", "query": {"education": "None"}},
    {"name": "Was born in Massachusetts", "query": {"birth_state": "Massachusetts"}},
    {"name": "Was born in Virginia", "query": {"birth_state": "Virginia"}},
    {"name": "Was born in Ohio", "query": {"birth_state": "Ohio"}},
    {"name": "Was a Republican", "query": {"party": "Republican"}},
    {"name": "Was a Democrat", "query": {"party": "Democratic"}},
    {"name": "Was a Democratic-Republican", "query": {"party": "Democratic-Republican"}},
    {"name": "Was a Whig", "query": {"party": "Whig"}},
    {"name": "Died in Virginia", "query": {"death_state": "Virginia"}},
    {"name": "Was not a Republican", "query": {"party": {"$ne": "Republican"}}},
    {"name": "Was not a Democrat", "query": {"party": {"$ne": "Democratic"}}},
    {"name": "Was neither a Democrat nor Republican", "query": {"party": {"$nin": ["Democrat", "Republican"]}}}
]

def select_prompts(prompts, collection_name):
    while True:
        top_prompts = random.sample(prompts, 2)
        remaining_prompts = [prompt for prompt in prompts if prompt not in top_prompts]
        side_prompts = random.sample(remaining_prompts, 2)
        
        all_combinations = [
            {"$and": [top_prompts[0]["query"], side_prompts[0]["query"]]},
            {"$and": [top_prompts[0]["query"], side_prompts[1]["query"]]},
            {"$and": [top_prompts[1]["query"], side_prompts[0]["query"]]},
            {"$and": [top_prompts[1]["query"], side_prompts[1]["query"]]}
        ]
        
        if all(collection_name.find_one(query) for query in all_combinations):
            matched_presidents = {
                "top1_side1": [doc["name"] for doc in collection_name.find(all_combinations[0])],
                "top1_side2": [doc["name"] for doc in collection_name.find(all_combinations[1])],
                "top2_side1": [doc["name"] for doc in collection_name.find(all_combinations[2])],
                "top2_side2": [doc["name"] for doc in collection_name.find(all_combinations[3])]
            }
            return {
                "top_prompts": [prompt["name"] for prompt in top_prompts],
                "side_prompts": [prompt["name"] for prompt in side_prompts],
                "matched_presidents": matched_presidents
            }